# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
tone_instructions: Prioritize technical optimality without being nitpicky.
early_access: true

reviews:
  request_changes_workflow: true
  high_level_summary: false
  auto_apply_labels: true
  auto_assign_reviewers: true

  path_filters:
    - "!**/bin/**"
    - "!**/obj/**"
    - "!**/*.generated.cs"

  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Apply C# standards:
        - SOLID: One public type per file, Strategy over switches, constructor injection
        - Types: Sealed by default, records for DTOs, nullable enabled
        - Control: Guard clauses first, early return, no arrow code
    - path: "**/Tests/**"
      instructions: |
        Focus on test coverage, assertion quality, edge cases.
        Use Method_Scenario_Outcome naming for test methods.
    - path: "**/src/**/*.cs"
      instructions: |
        Check: guard clauses at method start, Result<T> for failures, XML docs on public members.
    - path: "docs/**"
      instructions: "Check for accuracy and completeness. Light review only."

  coding_guidelines:
    - title: C# SOLID Principles
      description: |
        Enforce SOLID constraints:
        SRP (one public type per file), OCP (Strategy pattern), LSP (no NotImplementedException),
        ISP (role-specific interfaces), DIP (constructor injection)
      file_patterns:
        - "**/*.cs"
    - title: Type Safety
      description: |
        Enable nullable reference types. Use sealed by default.
        Prefer records for immutable data. Use pattern matching for type checks.
      file_patterns:
        - "**/*.cs"
    - title: Documentation
      description: |
        All public members require XML documentation with <summary>, <param>, <returns>.
        Use <list> and <para> for complex explanations.
      file_patterns:
        - "**/*.cs"

  auto_review:
    ignore_usernames:
      - "renovate[bot]"

  pre_merge_checks:
    issue_assessment:
      mode: warning
