// -----------------------------------------------------------------------
// <copyright file="FileHeaderHelper.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Agentic.Workflow.Generators.Polyfills;

namespace Agentic.Workflow.Generators.Helpers;

/// <summary>
/// Provides helper methods for generating common file headers in source generators.
/// </summary>
internal static class FileHeaderHelper
{
    /// <summary>
    /// Appends the standard auto-generated file header with nullable enable directive.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="sb"/> is null.</exception>
    public static void AppendAutoGeneratedHeader(StringBuilder sb)
    {
        ThrowHelper.ThrowIfNull(sb, nameof(sb));

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends a file-scoped namespace declaration.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="namespace">The namespace name.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="sb"/> or <paramref name="namespace"/> is null.</exception>
    public static void AppendNamespace(StringBuilder sb, string @namespace)
    {
        ThrowHelper.ThrowIfNull(sb, nameof(sb));
        ThrowHelper.ThrowIfNull(@namespace, nameof(@namespace));

        sb.AppendLine($"namespace {@namespace};");
        sb.AppendLine();
    }

    /// <summary>
    /// Appends using directives for the specified namespaces.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="namespaces">The namespaces to include in using directives.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="sb"/> is null.</exception>
    public static void AppendUsings(StringBuilder sb, params string[] namespaces)
    {
        ThrowHelper.ThrowIfNull(sb, nameof(sb));
        ThrowHelper.ThrowIfNull(namespaces, nameof(namespaces));

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
    }
}