// -----------------------------------------------------------------------
// <copyright file="WorkflowTelemetry.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Agentic.Workflow.Agents.Telemetry;

/// <summary>
/// Provides OpenTelemetry instrumentation for workflow step execution.
/// </summary>
/// <remarks>
/// <para>
/// This class defines the ActivitySource and Meters used to instrument
/// workflow step handlers generated by the Agentic.Workflow source generators.
/// </para>
/// <para>
/// Telemetry sources must be registered with OpenTelemetry in ServiceDefaults:
/// </para>
/// <code>
/// .WithTracing(tracing => tracing
///     .AddSource(WorkflowTelemetry.SourceName))
/// .WithMetrics(metrics => metrics
///     .AddMeter(WorkflowTelemetry.MeterName))
/// </code>
/// </remarks>
public static class WorkflowTelemetry
{
    /// <summary>
    /// The name of the workflow step ActivitySource for tracing.
    /// </summary>
    public const string SourceName = "Agentic.Workflow.Steps";

    /// <summary>
    /// The name of the workflow step Meter for metrics.
    /// </summary>
    public const string MeterName = "Agentic.Workflow.Steps";

    /// <summary>
    /// The version of the telemetry instrumentation.
    /// </summary>
    private const string Version = "1.0.0";

    /// <summary>
    /// ActivitySource for workflow step operations.
    /// </summary>
    public static readonly ActivitySource StepSource = new(SourceName, Version);

    /// <summary>
    /// Meter for workflow step metrics.
    /// </summary>
    public static readonly Meter StepMeter = new(MeterName, Version);

    #region Metrics Instruments

    /// <summary>
    /// Counter for completed steps, tagged by step name and outcome.
    /// </summary>
    public static readonly Counter<long> StepCompletedCounter = StepMeter.CreateCounter<long>(
        "agentic.step.completed",
        unit: "{steps}",
        description: "Number of completed workflow steps by name and outcome");

    /// <summary>
    /// Histogram for step duration in milliseconds.
    /// </summary>
    public static readonly Histogram<double> StepDurationHistogram = StepMeter.CreateHistogram<double>(
        "agentic.step.duration",
        unit: "ms",
        description: "Duration of workflow step execution in milliseconds");

    /// <summary>
    /// Counter for step failures, tagged by step name and error type.
    /// </summary>
    public static readonly Counter<long> StepFailureCounter = StepMeter.CreateCounter<long>(
        "agentic.step.failures",
        unit: "{failures}",
        description: "Number of workflow step failures by name and error type");

    #endregion

    #region Span Attribute Keys

    /// <summary>
    /// Attribute keys for step spans.
    /// </summary>
    public static class Attributes
    {
        /// <summary>Workflow identifier.</summary>
        public const string WorkflowId = "workflow.id";

        /// <summary>Step name.</summary>
        public const string StepName = "step.name";

        /// <summary>Step execution identifier.</summary>
        public const string StepExecutionId = "step.execution_id";

        /// <summary>Step duration in milliseconds.</summary>
        public const string StepDurationMs = "step.duration_ms";

        /// <summary>Step confidence score (0-1).</summary>
        public const string StepConfidence = "step.confidence";

        /// <summary>Error type for failed steps.</summary>
        public const string ErrorType = "error.type";

        /// <summary>Error message for failed steps.</summary>
        public const string ErrorMessage = "error.message";
    }

    #endregion

    #region Helper Methods

    /// <summary>
    /// Creates a new step execution span with standard attributes.
    /// </summary>
    /// <param name="stepName">The name of the step being executed.</param>
    /// <param name="workflowId">The workflow identifier.</param>
    /// <param name="kind">The span kind (default: Internal).</param>
    /// <returns>A new activity, or null if no listeners are registered.</returns>
    public static Activity? StartStepSpan(string stepName, Guid workflowId, ActivityKind kind = ActivityKind.Internal)
    {
        return StepSource.StartActivity($"step.{stepName}", kind)?
            .SetTag(Attributes.WorkflowId, workflowId.ToString())
            .SetTag(Attributes.StepName, stepName);
    }

    /// <summary>
    /// Records step completion metrics.
    /// </summary>
    /// <param name="stepName">The name of the step.</param>
    /// <param name="success">Whether the step completed successfully.</param>
    /// <param name="durationMs">The step duration in milliseconds.</param>
    /// <param name="confidence">The confidence score (optional).</param>
    public static void RecordStepCompletion(string stepName, bool success, double durationMs, double? confidence = null)
    {
        var tags = new TagList
        {
            { Attributes.StepName, stepName },
            { "outcome", success ? "success" : "failure" },
        };

        StepCompletedCounter.Add(1, tags);
        StepDurationHistogram.Record(durationMs, tags);

        if (!success)
        {
            StepFailureCounter.Add(1, tags);
        }
    }

    /// <summary>
    /// Records step failure metrics.
    /// </summary>
    /// <param name="stepName">The name of the step.</param>
    /// <param name="errorType">The type of error that occurred.</param>
    /// <param name="durationMs">The step duration in milliseconds.</param>
    public static void RecordStepFailure(string stepName, string errorType, double durationMs)
    {
        var tags = new TagList
        {
            { Attributes.StepName, stepName },
            { Attributes.ErrorType, errorType },
        };

        StepFailureCounter.Add(1, tags);
        StepDurationHistogram.Record(durationMs, tags);
    }

    #endregion
}
