// =============================================================================
// <copyright file="CoderState.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// =============================================================================

using Agentic.Workflow.Abstractions;
using Agentic.Workflow.Attributes;

namespace AgenticCoder.State;

/// <summary>
/// Represents the state of an agentic coding workflow.
/// </summary>
/// <remarks>
/// <para>
/// Tracks the coding task, plan, attempts, and test results through
/// the iterative refinement process.
/// </para>
/// </remarks>
[WorkflowState]
public sealed record CoderState : IWorkflowState
{
    /// <inheritdoc/>
    public Guid WorkflowId { get; init; }

    /// <summary>
    /// Gets the description of the coding task to implement.
    /// </summary>
    public string TaskDescription { get; init; } = string.Empty;

    /// <summary>
    /// Gets the implementation plan generated by the AI.
    /// </summary>
    public string? Plan { get; init; }

    /// <summary>
    /// Gets the history of code generation attempts.
    /// </summary>
    /// <remarks>
    /// This collection accumulates across iterations for audit trail.
    /// </remarks>
    [Append]
    public IReadOnlyList<CodeAttempt> Attempts { get; init; } = [];

    /// <summary>
    /// Gets the latest test execution results.
    /// </summary>
    public TestResults? LatestTestResults { get; init; }

    /// <summary>
    /// Gets the current attempt count.
    /// </summary>
    public int AttemptCount { get; init; }

    /// <summary>
    /// Gets a value indicating whether the implementation has been approved by a human.
    /// </summary>
    public bool HumanApproved { get; init; }
}

/// <summary>
/// Represents a single code generation attempt.
/// </summary>
/// <param name="Code">The generated code.</param>
/// <param name="Reasoning">The AI's reasoning for this implementation.</param>
/// <param name="Timestamp">When the attempt was made.</param>
public sealed record CodeAttempt(
    string Code,
    string Reasoning,
    DateTimeOffset Timestamp);

/// <summary>
/// Represents the results of running tests.
/// </summary>
/// <param name="Passed">Whether all tests passed.</param>
/// <param name="Failures">List of failure messages if any tests failed.</param>
public sealed record TestResults(
    bool Passed,
    IReadOnlyList<string> Failures);
